### ISSUE TITLE
PYTHON DEPENDENCIES installed successfully but dag_numpyro() not working....

### ISSUE THREAD

**Issue by SJLAMMY** [flyaflya/causact#60]
By following the [instructions](https://www.causact.com/install-causacts-python-dependencies#install-causacts-python-dependencies)  carefully & step-by-step, I have installed the new version of the causact and the PYTHON DEPENDENCIES packages successfully. However, dag_numpyro() does not work. Every time I tried #### STEP 3:  TEST THE INSTALLATION, it gives me the following error

> drawsDF = graph %>% dag_numpyro() ## see "sample:..."
Error in py_run_string_impl(code, local, convert) :
TypeError: the first argument must be callable
Run `reticulate::py_last_error()` for details. 
![causact](https://github.com/flyaflya/causact/assets/145883005/14f141a7-5f42-4e8e-a2d9-664cf2289902)

I've also tried deinstalling & reinstalling everything: R+RStudio+causact+Dependencies, but still have no luck!
Any suggestion? Thanks!

P.S. Last year, I have installed and used v0.4.2 of the causact package & dependencies without any problem.

**Comment by flyaflya** [comment]
can you post the output from:

```
graph %>% dag_numpyro(mcmc=FALSE)
```

I think your installation is fine and this may be a bug related to a special character.



On Sep 23, 2023, at 10:16 PM, SJLAMMY ***@***.***> wrote:

﻿

By following the instructions<https://www.causact.com/install-causacts-python-dependencies#install-causacts-python-dependencies> carefully & step-by-step, I have installed the new version of the causact and the PYTHON DEPENDENCIES packages successfully. However, dag_numpyro() does not work. Every time I tried #### STEP 3: TEST THE INSTALLATION, it gives me the following error

drawsDF = graph %>% dag_numpyro() ## see "sample:..."
Error in py_run_string_impl(code, local, convert) :
TypeError: the first argument must be callable
Run reticulate::py_last_error() for details.
[causact]<https://user-images.githubusercontent.com/145883005/270140811-14f141a7-5f42-4e8e-a2d9-664cf2289902.jpg>

I've also tried deinstalling & reinstalling everything: R+RStudio+causact+Dependencies, but still have no luck!
Any suggestion? Thanks!

P.S. Last year, I have installed and used v0.4.2 of the causact package & dependencies without any problem.

**Comment by SJLAMMY** [comment]
> graph %>% dag_numpyro(mcmc=FALSE)

## The below code will return a posterior distribution 
## for the given DAG. Use dag_numpyro(mcmc=TRUE) to return a
## data frame of the posterior distribution: 
reticulate::py_run_string("
import numpy as np
import numpyro as npo
import numpyro.distributions as dist
import pandas as pd
import arviz as az
from jax import random
from numpyro.infer import MCMC, NUTS
from jax.numpy import transpose as t
from jax.numpy import (exp, log, log1p, expm1, abs, mean,
                 sqrt, sign, round, concatenate, atleast_1d,
                 cos, sin, tan, cosh, sinh, tanh,
                 sum, prod, min, max, cumsum, cumprod )
## note that above is from JAX numpy package, not numpy.

def graph_model():
	## Define random variables and their relationships
	N_RV = npo.sample('N_RV', dist.Normal(0,10))


# computationally get posterior
mcmc = MCMC(NUTS(graph_model), num_warmup = 1000, num_samples = 4000)
rng_key = random.PRNGKey(seed = 111)
mcmc.run(rng_key)
drawsDS = az.from_numpyro(mcmc).posterior
# prepare xarray dataset for export to R dataframe
dimensions_to_keep = ['chain','draw']
drawsDS = drawsDS.squeeze(drop = True ).drop_dims([dim for dim in drawsDS.dims if dim not in dimensions_to_keep])
# unstack plate variables to flatten dataframe as needed

drawsDF = drawsDS.squeeze().to_dataframe()"
) ## END PYTHON STRING
drawsDF = reticulate::py$drawsDF
![image](https://github.com/flyaflya/causact/assets/145883005/b3e7cad7-cd8a-4847-8300-7818f51136a4)

**Comment by flyaflya** [comment]
Thanks for trying this.  Unfortunately, I do not see an obvious issue.  Maybe it is your setup.

Can you send Restart your R Session, then load `causact` with:

```
library(causact)
```

And then run:

```
reticulate::py_config()
```

My output looks like this, I am wondering if yours will be the same.

```
python:         C:/Users/ajf.BUEC-0F00TVX/AppData/Local/r-miniconda/envs/r-causact/python.exe
libpython:      C:/Users/ajf.BUEC-0F00TVX/AppData/Local/r-miniconda/envs/r-causact/python311.dll
pythonhome:     C:/Users/ajf.BUEC-0F00TVX/AppData/Local/r-miniconda/envs/r-causact
version:        3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/ajf.BUEC-0F00TVX/AppData/Local/r-miniconda/envs/r-causact/Lib/site-packages/numpy
numpy_version:  1.25.2

NOTE: Python version was forced by use_python() function
```

Thanks for your patience with this debugging.

**Comment by SJLAMMY** [comment]
> reticulate::py_config()
python:         C:/Users/TEMP.DESKTOP-KVJDR8G.001/AppData/Local/r-miniconda/envs/r-causact/python.exe
libpython:      C:/Users/TEMP.DESKTOP-KVJDR8G.001/AppData/Local/r-miniconda/envs/r-causact/python311.dll
pythonhome:     C:/Users/TEMP.DESKTOP-KVJDR8G.001/AppData/Local/r-miniconda/envs/r-causact
version:        3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:23:48) [MSC v.1936 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/TEMP.DESKTOP-KVJDR8G.001/AppData/Local/r-miniconda/envs/r-causact/Lib/site-packages/numpy
numpy_version:  1.26.0

NOTE: Python version was forced by use_python() function
![image](https://github.com/flyaflya/causact/assets/145883005/92852be3-a0dd-47ba-9ab6-ba022ef2335f)


Thank you very much for your response! I really appreciate your causact package and would like to be able to use it again. By the way, before the aforementioned problem is fixed, is it possible to make  v0.4.2 of the causact package available? I have tried  and got the following error message:

> remotes::install_github("flyaflya/causact@0.4.2")
Error: Failed to install 'causact' from GitHub:
  cannot open URL 'https://api.github.com/repos/flyaflya/causact/commits/0.4.2'

**Comment by SJLAMMY** [comment]
> The other thing I wonder is if you restart R, then copy and paste the below code, do you get the same error?
Unfortunately, I still got the same error
![image](https://github.com/flyaflya/causact/assets/145883005/21dbccdc-1ae3-4d3a-98a6-271647abce1e)

> reticulate::py_last_error()

> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\numpyro\__init__.py", line 6, in <module>
    from numpyro import compat, diagnostics, distributions, handlers, infer, ops, optim
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\numpyro\distributions\__init__.py", line 4, in <module>
    from numpyro.distributions.conjugate import (
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\numpyro\distributions\conjugate.py", line 9, in <module>
    from numpyro.distributions.continuous import Beta, Dirichlet, Gamma
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\numpyro\distributions\continuous.py", line 53, in <module>
    from numpyro.distributions.discrete import _to_logits_bernoulli
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\numpyro\distributions\discrete.py", line 37, in <module>
    from numpyro.distributions import constraints, transforms
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\numpyro\distributions\transforms.py", line 25, in <module>
    from numpyro.util import find_stack_level, not_jax_tracer
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\numpyro\util.py", line 15, in <module>
    from tqdm.auto import tqdm as tqdm_auto
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\tqdm\auto.py", line 23, in <module>
    from .asyncio import tqdm as asyncio_tqdm
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\site-packages\tqdm\asyncio.py", line 10, in <module>
    import asyncio
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\asyncio\__init__.py", line 42, in <module>
    from .windows_events import *
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\asyncio\windows_events.py", line 25, in <module>
    from . import windows_utils
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
             ^^^^^^
  File "C:\Program Files\R\R-4.3.1\library\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMINI~1\AppData\Local\R-MINI~1\envs\R-CAUS~1\Lib\asyncio\windows_utils.py", line 125, in <module>
    class Popen(subprocess.Popen):
TypeError: the first argument must be callable

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::py_run_string("\nimport numpy as np\nimport numpyro as npo\nimport numpyro.distributions as dist\nimport pandas as pd\nimport arviz as az\nfrom jax import random\nfrom numpyro.infer import MCMC, NUTS\nfrom jax.numpy import transpose as t\nfrom jax.numpy import (exp, log, log1p, expm1, abs, mean,\n                       sqrt, sign, round, concatenate, atleast_1d,\n                       cos, sin, tan, cosh, sinh, tanh,\n                       sum, prod, min, max, cumsum, cumprod )\n#note that above is from JAX numpy package, not numpy.\ndef graph_model():\n    ## Define random variables and their relationships\n    N_RV = npo.sample('N_RV', dist.Normal(0,10))\n#computationally get posterior\nmcmc = MCMC(NUTS(graph_model), num_warmup = 1000, num_samples = 4000)\nrng_key = random.PRNGKey(seed = 111)\nmcmc.run(rng_key)\n")
 2.   └─reticulate:::py_run_string_impl(code, local, convert)

**Comment by flyaflya** [comment]
Cool!  I think we have a fix.  The bug is in the `reticulate` package that `causact` depends on.  See here:

https://github.com/rstudio/reticulate/issues/1478

The September 11 release of reticulate (v1.32) has caused the issue.  You can install the dev version or the older 1.31 version.

Either way requires you to install RTOOLS:
https://cran.r-project.org/bin/windows/Rtools/rtools43/rtools.html

Then run this to get the dev version:
```
# install.packages("pak")
pak::pak("rstudio/reticulate")
```

The alternative is to wait for the next CRAN release of reticulate, but that could be a while.

Thanks SO MUCH for reporting this bug and let us all know if this path fixes it.

**Comment by flyaflya** [comment]
great.  thanks for reporting the bug, this bug will effect alot of people I teach over the next couple of weeks.  I've updated install instructions on the readme for those who experience the same problem in this commit: 8e8928d.
